### ISSUE TITLE
Failure in multimodule project

### ISSUE THREAD

**Issue by sbolotovms** [nebula-plugins/gradle-lint-plugin#176]
Hi, when running plugin against my project I ran into this issue:

```
15:38:07.804 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
15:38:07.805 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] FAILURE: Build failed with an exception.
15:38:07.805 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
15:38:07.805 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * What went wrong:
15:38:07.805 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] Cannot cast object 'submodule\build\intermediates\classes\debug' with class 'java.io.File' to class 'org.gradle.api.file.FileCollection'
15:38:07.805 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
15:38:07.805 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Exception is:
15:38:07.805 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] org.codehaus.groovy.runtime.typehandling.GroovyCastException: Cannot cast object 'submodule\build\intermediates\classes\debug' with class 'java.io.File' to class 'org.gradle.api.file.FileCollection'
15:38:07.805 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.rule.dependency.DependencyService.sourceSetOutput(DependencyService.groovy:439)
15:38:07.805 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.rule.dependency.DependencyService.memoizedMethodPriv$classReferencesString(DependencyService.groovy:167)
15:38:07.805 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.rule.dependency.DependencyService$_closure3.doCall(DependencyService.groovy)
15:38:07.805 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.rule.dependency.DependencyService.classReferences(DependencyService.groovy)
15:38:07.805 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.rule.dependency.DependencyService.memoizedMethodPriv$unusedDependenciesString(DependencyService.groovy:299)
15:38:07.805 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.rule.dependency.DependencyService$_closure8.doCall(DependencyService.groovy)
15:38:07.805 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.rule.dependency.DependencyService.unusedDependencies(DependencyService.groovy)
15:38:07.805 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.rule.dependency.DependencyService$unusedDependencies$8.call(Unknown Source)
15:38:07.805 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.rule.dependency.UnusedDependencyRule.visitGradleDependency(UnusedDependencyRule.groovy:57)
15:38:07.805 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.rule.GradleLintRule.this$dist$invoke$2(GradleLintRule.groovy)
15:38:07.805 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.rule.GradleLintRule$1.methodMissing(GradleLintRule.groovy)
15:38:07.805 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.rule.GradleLintRule$1.this$dist$invoke$3(GradleLintRule.groovy)
15:38:07.805 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.rule.GradleLintRule$1$2.methodMissing(GradleLintRule.groovy)
15:38:07.805 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.rule.GradleLintRule$1$2.visitMethodCallInDependencies(GradleLintRule.groovy:435)
15:38:07.805 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.rule.GradleLintRule$1$2.visitMethodCallExpression(GradleLintRule.groovy:247)
15:38:07.805 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.rule.CompositeGroovyAstVisitor$_visitMethodCallExpression_closure31.doCall(CompositeGroovyAstVisitor.groovy:284)
15:38:07.805 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.rule.CompositeGroovyAstVisitor.visitMethodCallExpression(CompositeGroovyAstVisitor.groovy:284)
15:38:07.805 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.rule.CompositeGroovyAstVisitor.super$3$visitExpressionStatement(CompositeGroovyAstVisitor.groovy)
15:38:07.805 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.rule.CompositeGroovyAstVisitor.visitExpressionStatement(CompositeGroovyAstVisitor.groovy:225)
15:38:07.805 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.rule.CompositeGroovyAstVisitor.super$3$visitBlockStatement(CompositeGroovyAstVisitor.groovy)
15:38:07.806 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.rule.CompositeGroovyAstVisitor.visitBlockStatement(CompositeGroovyAstVisitor.groovy:189)
15:38:07.806 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.rule.CompositeGroovyAstVisitor.super$2$visitClosureExpression(CompositeGroovyAstVisitor.groovy)
15:38:07.806 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.rule.CompositeGroovyAstVisitor.visitClosureExpression(CompositeGroovyAstVisitor.groovy:347)
15:38:07.806 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.rule.CompositeGroovyAstVisitor.super$2$visitListOfExpressions(CompositeGroovyAstVisitor.groovy)
15:38:07.806 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.rule.CompositeGroovyAstVisitor.visitListOfExpressions(CompositeGroovyAstVisitor.groovy:473)
15:38:07.806 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.rule.CompositeGroovyAstVisitor.super$2$visitTupleExpression(CompositeGroovyAstVisitor.groovy)
15:38:07.806 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.rule.CompositeGroovyAstVisitor.visitTupleExpression(CompositeGroovyAstVisitor.groovy:353)
15:38:07.806 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.rule.CompositeGroovyAstVisitor.super$2$visitArgumentlistExpression(CompositeGroovyAstVisitor.groovy)
15:38:07.806 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.rule.CompositeGroovyAstVisitor.visitArgumentlistExpression(CompositeGroovyAstVisitor.groovy:479)
15:38:07.806 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.rule.CompositeGroovyAstVisitor.super$2$visitMethodCallExpression(CompositeGroovyAstVisitor.groovy)
15:38:07.806 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.rule.CompositeGroovyAstVisitor.visitMethodCallExpression(CompositeGroovyAstVisitor.groovy:286)
15:38:07.806 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.rule.CompositeGroovyAstVisitor.super$3$visitExpressionStatement(CompositeGroovyAstVisitor.groovy)
15:38:07.806 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.rule.CompositeGroovyAstVisitor.visitExpressionStatement(CompositeGroovyAstVisitor.groovy:225)
15:38:07.806 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.rule.CompositeGroovyAstVisitor.super$3$visitBlockStatement(CompositeGroovyAstVisitor.groovy)
15:38:07.806 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.rule.CompositeGroovyAstVisitor.visitBlockStatement(CompositeGroovyAstVisitor.groovy:189)
15:38:07.806 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.rule.CompositeGroovyAstVisitor.super$3$visitClassCodeContainer(CompositeGroovyAstVisitor.groovy)
15:38:07.806 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.rule.CompositeGroovyAstVisitor.visitClassCodeContainer(CompositeGroovyAstVisitor.groovy:136)
15:38:07.806 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.rule.CompositeGroovyAstVisitor.super$3$visitConstructorOrMethod(CompositeGroovyAstVisitor.groovy)
15:38:07.806 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.rule.CompositeGroovyAstVisitor.visitConstructorOrMethod(CompositeGroovyAstVisitor.groovy:147)
15:38:07.806 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.rule.CompositeGroovyAstVisitor.super$3$visitMethod(CompositeGroovyAstVisitor.groovy)
15:38:07.806 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.rule.CompositeGroovyAstVisitor.visitMethod(CompositeGroovyAstVisitor.groovy:159)
15:38:07.806 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.rule.CompositeGroovyAstVisitor.super$3$visitClass(CompositeGroovyAstVisitor.groovy)
15:38:07.806 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.rule.CompositeGroovyAstVisitor.visitClass(CompositeGroovyAstVisitor.groovy:105)
15:38:07.806 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.org.codenarc.rule.AbstractAstVisitorRule.applyTo(AbstractAstVisitorRule.java:97)
15:38:07.806 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.org.codenarc.rule.AbstractRule.applyTo(AbstractRule.java:142)
15:38:07.806 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.org.codenarc.rule.Rule$applyTo$0.call(Unknown Source)
15:38:07.806 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.rule.GradleLintRule.applyTo(GradleLintRule.groovy:184)
15:38:07.806 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.org.codenarc.rule.Rule$applyTo$0.call(Unknown Source)
15:38:07.806 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.org.codenarc.rule.Rule$applyTo$0.call(Unknown Source)
15:38:07.806 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.org.codenarc.analyzer.AbstractSourceAnalyzer.collectViolations(AbstractSourceAnalyzer.groovy:40)
15:38:07.807 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.plugin.LintService$ReportableAnalyzer.analyze(LintService.groovy:50)
15:38:07.807 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.plugin.LintService$ReportableAnalyzer$analyze.call(Unknown Source)
15:38:07.807 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.plugin.LintService$_lint_closure5.doCall(LintService.groovy:122)
15:38:07.807 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.plugin.LintService.lint(LintService.groovy:111)
15:38:07.807 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.plugin.LintService$lint.call(Unknown Source)
15:38:07.807 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.plugin.LintGradleTask.lint(LintGradleTask.groovy:37)
15:38:07.807 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.plugin.LintGradleTask$lint.call(Unknown Source)
15:38:07.807 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.netflix.nebula.lint.plugin.GradleLintPlugin$1.buildFinished(GradleLintPlugin.groovy:66)
15:38:07.807 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:35)
15:38:07.807 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.dispatch.ReflectionDispatch.dispatch(ReflectionDispatch.java:24)
15:38:07.807 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:371)
15:38:07.807 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.event.DefaultListenerManager$ListenerDetails.dispatch(DefaultListenerManager.java:353)
15:38:07.807 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
15:38:07.807 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:341)
15:38:07.807 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.event.DefaultListenerManager$EventBroadcast$ListenerDispatch.dispatch(DefaultListenerManager.java:328)
15:38:07.807 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:42)
15:38:07.807 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:230)
15:38:07.807 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.event.BroadcastDispatch$SingletonDispatch.dispatch(BroadcastDispatch.java:149)
15:38:07.807 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.event.AbstractBroadcastDispatch.dispatch(AbstractBroadcastDispatch.java:58)
15:38:07.807 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:324)
15:38:07.807 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.event.BroadcastDispatch$CompositeDispatch.dispatch(BroadcastDispatch.java:234)
15:38:07.807 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:140)
15:38:07.807 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.event.ListenerBroadcast.dispatch(ListenerBroadcast.java:37)
15:38:07.807 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.dispatch.ProxyDispatchAdapter$DispatchingInvocationHandler.invoke(ProxyDispatchAdapter.java:93)
15:38:07.807 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at com.sun.proxy.$Proxy17.buildFinished(Unknown Source)
15:38:07.807 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.initialization.DefaultGradleLauncher.finishBuild(DefaultGradleLauncher.java:146)
15:38:07.807 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:136)
15:38:07.807 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.initialization.DefaultGradleLauncher.executeTasks(DefaultGradleLauncher.java:107)
15:38:07.807 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:78)
15:38:07.807 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.invocation.GradleBuildController$1.call(GradleBuildController.java:75)
15:38:07.808 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.work.DefaultWorkerLeaseService.withLocks(DefaultWorkerLeaseService.java:152)
15:38:07.808 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.invocation.GradleBuildController.doBuild(GradleBuildController.java:100)
15:38:07.808 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.invocation.GradleBuildController.run(GradleBuildController.java:75)
15:38:07.808 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
15:38:07.808 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
15:38:07.808 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.tooling.internal.provider.ValidatingBuildActionRunner.run(ValidatingBuildActionRunner.java:32)
15:38:07.808 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner$1.run(RunAsBuildOperationBuildActionRunner.java:43)
15:38:07.808 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
15:38:07.808 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
15:38:07.808 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:197)
15:38:07.808 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:107)
15:38:07.808 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.exec.RunAsBuildOperationBuildActionRunner.run(RunAsBuildOperationBuildActionRunner.java:40)
15:38:07.808 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.tooling.internal.provider.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:51)
15:38:07.808 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:45)
15:38:07.808 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:29)
15:38:07.808 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:39)
15:38:07.808 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.exec.BuildTreeScopeBuildActionExecuter.execute(BuildTreeScopeBuildActionExecuter.java:25)
15:38:07.808 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:71)
15:38:07.808 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:45)
15:38:07.808 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:51)
15:38:07.808 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.tooling.internal.provider.ServicesSetupBuildActionExecuter.execute(ServicesSetupBuildActionExecuter.java:32)
15:38:07.808 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:36)
15:38:07.808 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.tooling.internal.provider.GradleThreadBuildActionExecuter.execute(GradleThreadBuildActionExecuter.java:25)
15:38:07.808 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:43)
15:38:07.808 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.tooling.internal.provider.ParallelismConfigurationBuildActionExecuter.execute(ParallelismConfigurationBuildActionExecuter.java:29)
15:38:07.808 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:64)
15:38:07.808 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.tooling.internal.provider.StartParamsValidatingActionExecuter.execute(StartParamsValidatingActionExecuter.java:29)
15:38:07.808 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:55)
15:38:07.808 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.tooling.internal.provider.SessionFailureReportingActionExecuter.execute(SessionFailureReportingActionExecuter.java:42)
15:38:07.808 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:58)
15:38:07.808 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.tooling.internal.provider.SetupLoggingActionExecuter.execute(SetupLoggingActionExecuter.java:33)
15:38:07.809 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:67)
15:38:07.809 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
15:38:07.809 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
15:38:07.809 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
15:38:07.809 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
15:38:07.809 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
15:38:07.809 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
15:38:07.809 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
15:38:07.809 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
15:38:07.809 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
15:38:07.809 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
15:38:07.809 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.util.Swapper.swap(Swapper.java:38)
15:38:07.809 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
15:38:07.809 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
15:38:07.809 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
15:38:07.809 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
15:38:07.809 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:62)
15:38:07.809 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
15:38:07.809 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
15:38:07.809 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:82)
15:38:07.809 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
15:38:07.809 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
15:38:07.809 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
15:38:07.809 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:297)
15:38:07.809 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:63)
15:38:07.809 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:46)
15:38:07.809 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]   at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:55)
15:38:07.809 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
15:38:07.809 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter]
15:38:07.809 [ERROR] [org.gradle.internal.buildevents.BuildExceptionReporter] * Get more help at https://help.gradle.org
15:38:07.810 [ERROR] [org.gradle.internal.buildevents.BuildResultLogger]
```

I used classpath dependency in `buildscript` and applied plugin in `allprojects`

Let me know if you need more than just a stack trace.

**Comment by chali** [comment]
Hi @sbolotovms, could you provide an example project where you see this failure?
