### ISSUE TITLE
NPE in 15.0.0: java.lang.NullPointerException at org.gradle.api.internal.artifacts.DefaultModuleVersionIdentifier.<init>(DefaultModuleVersionIdentifier.java:34)

### ISSUE THREAD

**Issue by MarcelBruch** [nebula-plugins/gradle-lint-plugin#258]
I'm trying 15.0.0 but quickly get the NPE below. I'm using Gradle 5.6.2.

I'm not sure if it's relevant but:

14.2.5 does some work - although it seems to have trouble with how I declare versions of my dependencies. I'm declaring the versions in the top-level build.gradle via dependencies { constraints { implementation "...:major.minor.micro"... and in the submodules I just declare the dependency w/o version numbers.

Let me know if I can provide more meaningful details.

Thanks,
Marcel

BUILD FAILED in 2s
1 actionable task: 1 executed
#:~/Git/$ gw lintGradle --stacktrace
Using gradle at '/Users/marcel/Git/p1/gradlew' to run buildfile '/Users/marcel/Git/p1/build.gradle':

> Task :lintGradle FAILED
Error from [com.netflix.nebula.lint.rule.GradleLintRule$1] processing source file [null]

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':lintGradle'.
> java.lang.NullPointerException (no error message)

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':lintGradle'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:166)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter$3.accept(ExecuteActionsTaskExecuter.java:163)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:191)
…
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)
Caused by: java.lang.NullPointerException
        at org.gradle.api.internal.artifacts.DefaultModuleVersionIdentifier.<init>(DefaultModuleVersionIdentifier.java:34)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
        at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
        at com.netflix.nebula.lint.rule.dependency.DependencyService$_findDeclaredDependencies_closure21$_closure55.doCall(DependencyService.groovy:311)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at com.netflix.nebula.lint.rule.dependency.DependencyService$_findDeclaredDependencies_closure21.doCall(DependencyService.groovy:311)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at com.netflix.nebula.lint.rule.dependency.DependencyService.findDeclaredDependencies(DependencyService.groovy:307)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at com.netflix.nebula.lint.rule.dependency.DependencyService.memoizedMethodPriv$undeclaredDependenciesString(DependencyService.groovy:300)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at com.netflix.nebula.lint.rule.dependency.DependencyService$_closure7.doCall(DependencyService.groovy)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at com.netflix.nebula.lint.rule.dependency.DependencyService.undeclaredDependencies(DependencyService.groovy)
        at com.netflix.nebula.lint.rule.dependency.DependencyService$undeclaredDependencies$5.call(Unknown Source)
        at com.netflix.nebula.lint.rule.dependency.UnusedDependencyRule$_visitClassComplete_closure3.doCall(UnusedDependencyRule.groovy:92)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at com.netflix.nebula.lint.rule.dependency.UnusedDependencyRule.visitClassComplete(UnusedDependencyRule.groovy:90)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at com.netflix.nebula.lint.rule.CompositeGroovyAstVisitor$_visitClass_closure2.doCall(CompositeGroovyAstVisitor.groovy:106)
        at jdk.internal.reflect.GeneratedMethodAccessor1884.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at com.netflix.nebula.lint.rule.CompositeGroovyAstVisitor.visitClass(CompositeGroovyAstVisitor.groovy:106)
        at com.netflix.nebula.lint.org.codenarc.rule.AbstractAstVisitorRule.applyTo(AbstractAstVisitorRule.java:97)
        at com.netflix.nebula.lint.org.codenarc.rule.AbstractRule.applyTo(AbstractRule.java:142)
        at com.netflix.nebula.lint.org.codenarc.rule.Rule$applyTo$0.call(Unknown Source)
        at com.netflix.nebula.lint.rule.GradleLintRule.applyTo(GradleLintRule.groovy:184)
        at com.netflix.nebula.lint.org.codenarc.rule.Rule$applyTo$0.call(Unknown Source)
        at com.netflix.nebula.lint.org.codenarc.rule.Rule$applyTo$0.call(Unknown Source)
        at com.netflix.nebula.lint.org.codenarc.analyzer.AbstractSourceAnalyzer.collectViolations(AbstractSourceAnalyzer.groovy:40)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at com.netflix.nebula.lint.plugin.LintService$ReportableAnalyzer.analyze(LintService.groovy:50)
        at com.netflix.nebula.lint.plugin.LintService$ReportableAnalyzer$analyze.call(Unknown Source)
        at com.netflix.nebula.lint.plugin.LintService$_lint_closure5.doCall(LintService.groovy:122)
        at jdk.internal.reflect.GeneratedMethodAccessor1680.invoke(Unknown Source)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at com.netflix.nebula.lint.plugin.LintService.lint(LintService.groovy:111)
        at com.netflix.nebula.lint.plugin.LintService$lint.call(Unknown Source)
        at com.netflix.nebula.lint.plugin.LintGradleTask.lint(LintGradleTask.groovy:47)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
   
        ... truncated.

* Get more help at https://help.gradle.org

BUILD FAILED in 1s
1 actionable task: 1 executed

**Comment by rpalcolea** [comment]
Hi @MarcelBruch , thanks for reporting this. Totally missed this scenario 

Added a test case so we don't miss it in the future.

https://github.com/nebula-plugins/gradle-lint-plugin/pull/259 takes care of it and I'm releasing 15.0.1 -> https://travis-ci.org/nebula-plugins/gradle-lint-plugin/builds/602407005.


Should be out soon!
