### ISSUE TITLE
Missing codenarc library

### ISSUE THREAD

**Issue by CSBaum** [nebula-plugins/gradle-lint-plugin#26]
It looks like v0.28.0 is missing the codenarc jar.  When i attempt to run any task I get the following error:
```
* What went wrong:
An exception occurred applying plugin request [id: 'nebula.lint', version: '0.28.0']
> Failed to apply plugin [id 'nebula.lint']
   > Could not create task of type 'LintGradleTask'.
```

I have attached the stacktrace which shows the root cause:
```
Caused by: java.lang.NoClassDefFoundError: org/codenarc/rule/Violation
        at com.netflix.nebula.lint.plugin.LintGradleTask$1.$getStaticMetaClass(LintGradleTask.groovy)
        at com.netflix.nebula.lint.GradleLintViolationAction.<init>(GradleLintViolationAction.groovy)
        at com.netflix.nebula.lint.plugin.LintGradleTask$1.<init>(LintGradleTask.groovy)
        at com.netflix.nebula.lint.plugin.LintGradleTask.<init>(LintGradleTask.groovy:47)
        at com.netflix.nebula.lint.plugin.LintGradleTask_Decorated.<init>(Unknown Source)
        at org.gradle.api.internal.DependencyInjectingInstantiator.newInstance(DependencyInjectingInstantiator.java:48)
        at org.gradle.api.internal.ClassGeneratorBackedInstantiator.newInstance(ClassGeneratorBackedInstantiator.java:36)
        at org.gradle.api.internal.project.taskfactory.TaskFactory$1.call(TaskFactory.java:121)
```
[lint-stacktrace.txt](https://github.com/nebula-plugins/gradle-lint-plugin/files/274872/lint-stacktrace.txt)

Thanks again for all the hard work you and your team is putting into this plugin!

Sean

**Comment by jkschneider** [comment]
The Gradle plugin portal’s proxy (https://plugins.gradle.org/m2/) is apparently case-insensitive in some way. When attempting to resolve the 0.25.2 version of Codenarc from the repository (e.g. https://plugins.gradle.org/m2/org/codenarc/), it sees these two directory listings, picks the lower cased one, and doesn't find 0.25.2 inside it. Evidently the plugins dsl proceeds to fail dependency resolution silently, resulting in this runtime issue later.

We'll go ahead and shade and pack codenarc inside of the plugin as well to circumvent this issue.

To solve immediately, simply bypass the plugin portal repository by adding:

```groovy
buildscript {
   repositories { mavenCentral() }
}
```

**Comment by jkschneider** [comment]
@DanielThomas @rspieldenner fyi
