### ISSUE TITLE
Dependency rules fail on project dependencies

### ISSUE THREAD

**Issue by DanielThomas** [nebula-plugins/gradle-lint-plugin#34]
Appears to go looking for the project artifact and fails:

    FAILURE: Build failed with an exception.

    * What went wrong:
    Execution failed for task ':lintGradle'.
    > java.lang.reflect.UndeclaredThrowableException (no error message)

    * Try:
    Run with --info or --debug option to get more log output.

    * Exception is:
    org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':lintGradle'.
     at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
     at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
     at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
     at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:68)
     at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
     at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
     at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
     at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
     at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
     at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
     at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
     at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
     at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
     at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
     at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
     at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
     at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
     at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
     at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
     at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
     at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
     at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
     at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:154)
     at org.gradle.internal.Factories$1.create(Factories.java:22)
     at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
     at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:52)
     at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:151)
     at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
     at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:99)
     at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:93)
     at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:90)
     at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:62)
     at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:93)
     at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:82)
     at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:94)
     at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
     at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
     at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:43)
     at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:28)
     at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
     at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
     at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:51)
     at org.gradle.launcher.exec.DaemonUsageSuggestingBuildActionExecuter.execute(DaemonUsageSuggestingBuildActionExecuter.java:28)
     at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:43)
     at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:173)
     at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:241)
     at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:214)
     at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
     at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
     at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:207)
     at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
     at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
     at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
     at org.gradle.launcher.Main.doAction(Main.java:33)
     at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
     at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:55)
     at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:36)
     at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
     at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
     at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:129)
     at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:61)
    Caused by: java.lang.reflect.UndeclaredThrowableException
     at jsr166y.ForkJoinTask.getThrowableException(ForkJoinTask.java:504)
     at jsr166y.ForkJoinTask.reportResult(ForkJoinTask.java:567)
     at jsr166y.ForkJoinTask.join(ForkJoinTask.java:611)
     at jsr166y.ForkJoinPool.invoke(ForkJoinPool.java:1492)
     at groovyx.gpars.extra166y.ParallelArrayWithMapping.apply(ParallelArrayWithMapping.java:48)
     at groovyx.gpars.extra166y.ParallelArray.apply(ParallelArray.java:329)
     at groovyx.gpars.pa.GParsPoolUtilHelper.eachParallelPA(GParsPoolUtilHelper.groovy:192)
     at groovyx.gpars.GParsPoolUtil.eachParallel(GParsPoolUtil.java:358)
     at com.netflix.nebula.lint.rule.dependency.DependencyService$_memoizedMethodPriv_artifactsByClassConfiguration_closure15.doCall(DependencyService.groovy:71)
     at groovyx.gpars.GParsPool$_withExistingPool_closure1.doCall(GParsPool.groovy:174)
     at groovyx.gpars.GParsPool$_withExistingPool_closure1.doCall(GParsPool.groovy)
     at groovyx.gpars.GParsPool.withExistingPool(GParsPool.groovy:173)
     at groovyx.gpars.GParsPool$withExistingPool$2.callStatic(Unknown Source)
     at groovyx.gpars.GParsPool.withPool(GParsPool.groovy:145)
     at groovyx.gpars.GParsPool$withPool$1.callStatic(Unknown Source)
     at groovyx.gpars.GParsPool.withPool(GParsPool.groovy:121)
     at groovyx.gpars.GParsPool$withPool$0.callStatic(Unknown Source)
     at groovyx.gpars.GParsPool.withPool(GParsPool.groovy:100)
     at groovyx.gpars.GParsPool$withPool.call(Unknown Source)
     at com.netflix.nebula.lint.rule.dependency.DependencyService.memoizedMethodPriv$artifactsByClassConfiguration(DependencyService.groovy:70)
     at com.netflix.nebula.lint.rule.dependency.DependencyService$_closure1.doCall(DependencyService.groovy)
     at com.netflix.nebula.lint.rule.dependency.DependencyService.artifactsByClass(DependencyService.groovy)
     at com.netflix.nebula.lint.rule.dependency.DependencyService$artifactsByClass$3.callCurrent(Unknown Source)
     at com.netflix.nebula.lint.rule.dependency.DependencyService.artifactsByClass(DependencyService.groovy:45)
     at com.netflix.nebula.lint.rule.dependency.DependencyService$artifactsByClass$2.call(Unknown Source)
     at com.netflix.nebula.lint.rule.dependency.DuplicateDependencyClassRule.visitGradleDependency(DuplicateDependencyClassRule.groovy:22)
     at com.netflix.nebula.lint.rule.GradleLintRule.this$dist$invoke$4(GradleLintRule.groovy)
     at com.netflix.nebula.lint.rule.GradleLintRule$1.methodMissing(GradleLintRule.groovy)
     at com.netflix.nebula.lint.rule.GradleLintRule$1.this$dist$invoke$3(GradleLintRule.groovy)
     at com.netflix.nebula.lint.rule.GradleLintRule$1$2.methodMissing(GradleLintRule.groovy)
     at com.netflix.nebula.lint.rule.GradleLintRule$1$2.visitMethodCallInDependencies(GradleLintRule.groovy:384)
     at com.netflix.nebula.lint.rule.GradleLintRule$1$2.visitMethodCallExpression(GradleLintRule.groovy:207)
     at com.netflix.nebula.lint.rule.GradleLintRule$1$2.super$3$visitExpressionStatement(GradleLintRule.groovy)
     at com.netflix.nebula.lint.rule.GradleLintRule$1$2.visitExpressionStatement(GradleLintRule.groovy:344)
     at com.netflix.nebula.lint.rule.GradleLintRule$1$2.super$2$visitMethodCallExpression(GradleLintRule.groovy)
     at com.netflix.nebula.lint.rule.GradleLintRule$1$2.visitMethodCallExpression(GradleLintRule.groovy:214)
     at com.netflix.nebula.lint.rule.GradleLintRule$1$2.super$3$visitExpressionStatement(GradleLintRule.groovy)
     at com.netflix.nebula.lint.rule.GradleLintRule$1$2.visitExpressionStatement(GradleLintRule.groovy:344)
     at com.netflix.nebula.lint.rule.GradleLintRule$1$3$_visitConstructorOrMethod_closure11.doCall(GradleLintRule.groovy:464)
     at com.netflix.nebula.lint.rule.GradleLintRule$1$3.both(GradleLintRule.groovy:408)
     at com.netflix.nebula.lint.rule.GradleLintRule$1$3$both.callCurrent(Unknown Source)
     at com.netflix.nebula.lint.rule.GradleLintRule$1$3.visitConstructorOrMethod(GradleLintRule.groovy:464)
     at com.netflix.nebula.lint.org.codenarc.rule.AbstractAstVisitor.visitMethod(AbstractAstVisitor.java:171)
     at com.netflix.nebula.lint.org.codenarc.rule.AbstractAstVisitor.visitClass(AbstractAstVisitor.java:148)
     at com.netflix.nebula.lint.org.codenarc.rule.AbstractAstVisitorRule.applyTo(AbstractAstVisitorRule.java:97)
     at com.netflix.nebula.lint.org.codenarc.rule.AbstractRule.applyTo(AbstractRule.java:142)
     at com.netflix.nebula.lint.org.codenarc.rule.Rule$applyTo$0.call(Unknown Source)
     at com.netflix.nebula.lint.rule.GradleLintRule.applyTo(GradleLintRule.groovy:134)
     at com.netflix.nebula.lint.org.codenarc.rule.Rule$applyTo$0.call(Unknown Source)
     at com.netflix.nebula.lint.org.codenarc.rule.Rule$applyTo$0.call(Unknown Source)
     at com.netflix.nebula.lint.org.codenarc.analyzer.AbstractSourceAnalyzer.collectViolations(AbstractSourceAnalyzer.groovy:40)
     at com.netflix.nebula.lint.plugin.LintService$ReportableAnalyzer.analyze(LintService.groovy:48)
     at com.netflix.nebula.lint.plugin.LintService$ReportableAnalyzer$analyze.call(Unknown Source)
     at com.netflix.nebula.lint.plugin.LintService$_lint_closure3.doCall(LintService.groovy:96)
     at com.netflix.nebula.lint.plugin.LintService.lint(LintService.groovy:93)
     at com.netflix.nebula.lint.plugin.LintService$lint.call(Unknown Source)
     at com.netflix.nebula.lint.plugin.LintGradleTask.lint(LintGradleTask.groovy:41)
     at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
     at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:228)
     at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
     at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
     at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
     at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
     at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
     at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
     ... 60 more
    Caused by: java.lang.reflect.UndeclaredThrowableException
     at jsr166y.ForkJoinTask.getThrowableException(ForkJoinTask.java:504)
     at jsr166y.ForkJoinTask.reportResult(ForkJoinTask.java:567)
     at jsr166y.ForkJoinTask.join(ForkJoinTask.java:611)
     at groovyx.gpars.extra166y.PAS$FJBase.internalCompute(PAS.java:120)
     at groovyx.gpars.extra166y.PAS$FJBase.compute(PAS.java:106)
     at jsr166y.RecursiveAction.exec(RecursiveAction.java:148)
     at jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:305)
     at jsr166y.ForkJoinWorkerThread.execTask(ForkJoinWorkerThread.java:575)
     at jsr166y.ForkJoinPool.scan(ForkJoinPool.java:755)
     at jsr166y.ForkJoinPool.work(ForkJoinPool.java:617)
     at jsr166y.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:369)
    Caused by: java.lang.reflect.UndeclaredThrowableException
     at jsr166y.ForkJoinTask.getThrowableException(ForkJoinTask.java:504)
     at jsr166y.ForkJoinTask.reportResult(ForkJoinTask.java:567)
     at jsr166y.ForkJoinTask.join(ForkJoinTask.java:611)
     at groovyx.gpars.extra166y.PAS$FJBase.internalCompute(PAS.java:120)
     at groovyx.gpars.extra166y.PAS$FJBase.compute(PAS.java:106)
     at jsr166y.RecursiveAction.exec(RecursiveAction.java:148)
     at jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:305)
     at jsr166y.ForkJoinWorkerThread.execTask(ForkJoinWorkerThread.java:575)
     at jsr166y.ForkJoinPool.scan(ForkJoinPool.java:733)
     ... 2 more
    Caused by: java.lang.reflect.UndeclaredThrowableException
     ... 11 more
    Caused by: java.lang.reflect.UndeclaredThrowableException
     at jsr166y.ForkJoinTask.getThrowableException(ForkJoinTask.java:504)
     at jsr166y.ForkJoinTask.reportResult(ForkJoinTask.java:567)
     at jsr166y.ForkJoinTask.join(ForkJoinTask.java:611)
     at groovyx.gpars.extra166y.PAS$FJBase.internalCompute(PAS.java:120)
     at groovyx.gpars.extra166y.PAS$FJBase.compute(PAS.java:106)
     at jsr166y.RecursiveAction.exec(RecursiveAction.java:148)
     at jsr166y.ForkJoinTask.doExec(ForkJoinTask.java:305)
     at jsr166y.ForkJoinWorkerThread.helpJoinTask(ForkJoinWorkerThread.java:783)
     at jsr166y.ForkJoinWorkerThread.joinTask(ForkJoinWorkerThread.java:698)
     at jsr166y.ForkJoinTask.doJoin(ForkJoinTask.java:333)
     at jsr166y.ForkJoinTask.join(ForkJoinTask.java:610)
     ... 8 more
    Caused by: java.lang.reflect.UndeclaredThrowableException
     at com.sun.proxy.$Proxy74.op(Unknown Source)
     at groovyx.gpars.extra166y.AbstractParallelAnyArray$OUPap.leafApply(AbstractParallelAnyArray.java:640)
     at groovyx.gpars.extra166y.PAS$FJOApply.atLeaf(PAS.java:147)
     at groovyx.gpars.extra166y.PAS$FJBase.internalCompute(PAS.java:118)
     ... 15 more
    Caused by: java.io.FileNotFoundException: /mnt/builds/slave/workspace/MCE-minions-deploy-from-bake~2/test-common/build/libs/minions-test-common-1.0.75.jar (No such file or directory)
     at com.netflix.nebula.lint.rule.dependency.DependencyService.memoizedMethodPriv$jarContentsFile(DependencyService.groovy:106)
     at com.netflix.nebula.lint.rule.dependency.DependencyService$__clinit__closure32.doCall(DependencyService.groovy)
     at com.netflix.nebula.lint.rule.dependency.DependencyService.jarContents(DependencyService.groovy)
     at com.netflix.nebula.lint.rule.dependency.DependencyService$_memoizedMethodPriv_artifactsByClassConfiguration_closure15$_closure38.doCall(DependencyService.groovy:78)
     at groovyx.gpars.pa.GParsPoolUtilHelper$_eachParallelPA_closure8.doCall(GParsPoolUtilHelper.groovy:192)
     ... 19 more

**Comment by jkschneider** [comment]
Duplicates #27
