### ISSUE TITLE
can't find subproject source code

### ISSUE THREAD

**Issue by johnscancella** [nebula-plugins/gradle-lint-plugin#41]
When trying to run the `generateGradleLintReport` from the root project directory it errors:
```
[jscancella@johns-air transfer (master)]$ gradle generateGradleLintReport
:generateGradleLintReport
Error from [com.netflix.nebula.lint.rule.GradleLintRule$1] processing source file [null]
:generateGradleLintReport FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':generateGradleLintReport'.
> gov/loc/repository/model/Ided

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.181 secs
```

And here is the build environment
```
[jscancella@johns-air transfer (master)]$ gradle buildenv
:buildEnvironment

------------------------------------------------------------
Root project
------------------------------------------------------------

classpath
\--- com.netflix.nebula:gradle-lint-plugin:latest.release -> 4.0.0
     +--- org.ow2.asm:asm:5.0.4
     +--- com.netflix.nebula:gradle-info-plugin:3.0.4
     |    +--- com.perforce:p4java-jfrog:2011.1.297684
     |    |    \--- com.jcraft:jzlib:1.0.7
     |    +--- com.netflix.nebula:gradle-contacts-plugin:2.2.0
     |    +--- org.eclipse.jgit:org.eclipse.jgit:3.2.0.201312181205-r
     |    |    +--- com.jcraft:jsch:0.1.46
     |    |    \--- com.googlecode.javaewah:JavaEWAH:0.5.6
     |    \--- org.tmatesoft.svnkit:svnkit:1.8.5
     |         +--- com.jcraft:jsch.agentproxy.svnkit-trilead-ssh2:0.0.7
     |         |    +--- com.trilead:trilead-ssh2:1.0.0-build217
     |         |    \--- com.jcraft:jsch.agentproxy.core:0.0.7
     |         +--- net.java.dev.jna:jna:3.5.2
     |         +--- org.tmatesoft.sqljet:sqljet:1.1.10
     |         |    \--- org.antlr:antlr-runtime:3.4
     |         +--- net.java.dev.jna:platform:3.5.2
     |         |    \--- net.java.dev.jna:jna:3.5.2
     |         +--- com.jcraft:jsch.agentproxy.connector-factory:0.0.7
     |         |    +--- com.jcraft:jsch.agentproxy.core:0.0.7
     |         |    +--- com.jcraft:jsch.agentproxy.usocket-jna:0.0.7
     |         |    |    +--- com.jcraft:jsch.agentproxy.core:0.0.7
     |         |    |    +--- net.java.dev.jna:jna:3.4.0 -> 3.5.2
     |         |    |    \--- net.java.dev.jna:platform:3.4.0 -> 3.5.2 (*)
     |         |    +--- com.jcraft:jsch.agentproxy.usocket-nc:0.0.7
     |         |    |    \--- com.jcraft:jsch.agentproxy.core:0.0.7
     |         |    +--- com.jcraft:jsch.agentproxy.sshagent:0.0.7
     |         |    |    \--- com.jcraft:jsch.agentproxy.core:0.0.7
     |         |    \--- com.jcraft:jsch.agentproxy.pageant:0.0.7
     |         |         +--- com.jcraft:jsch.agentproxy.core:0.0.7
     |         |         +--- net.java.dev.jna:jna:3.4.0 -> 3.5.2
     |         |         \--- net.java.dev.jna:platform:3.4.0 -> 3.5.2 (*)
     |         +--- de.regnis.q.sequence:sequence-library:1.0.2
     |         \--- com.trilead:trilead-ssh2:1.0.0-build217
     +--- commons-lang:commons-lang:2.6
     +--- org.eclipse.jdt:core:3.1.1
     +--- org.codehaus.gpars:gpars:1.2.1
     |    +--- org.multiverse:multiverse-core:0.7.0
     |    \--- org.codehaus.jsr166-mirror:jsr166y:1.7.0
     \--- junit:junit:4.12
          \--- org.hamcrest:hamcrest-core:1.3

(*) - dependencies omitted (listed previously)
:lintGradle
Error from [com.netflix.nebula.lint.rule.GradleLintRule$1] processing source file [null]
:lintGradle FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':lintGradle'.
> gov/loc/repository/model/Ided

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 1.249 secs
```

**Comment by jkschneider** [comment]
@johnscancella Attempted to recreate this with the test in abe3094. Could you take a look and tell me what is different about your setup or run again with --stacktrace and provide the stacktrace? Thanks!

**Comment by johnscancella** [comment]
Attached is the build directory zipped up so you can look at the generated reports.
[build.zip](https://github.com/nebula-plugins/gradle-lint-plugin/files/390451/build.zip)

Here is the output from gradle during the run:
```
[jscancella@johns-air gradle-lint-plugin (master)]$ gradle clean test --stacktrace
Inferred project: gradle-lint-plugin, version: 4.1.0-dev.3+abe3094
:clean
:compileJava UP-TO-DATE
:compileGroovy
:pluginDescriptors
:processResources
:classes
:pluginUnderTestMetadata
:compileTestJava UP-TO-DATE
:compileTestGroovy
:processTestResources UP-TO-DATE
:testClasses
:test
objc[29047]: Class JavaLaunchHelper is implemented in both /Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/bin/java and /Library/Java/JavaVirtualMachines/jdk1.7.0_80.jdk/Contents/Home/jre/lib/libinstrument.dylib. One of the two will be used. Which one is undefined.

com.netflix.nebula.lint.rule.dependency.DependencyServiceSpec > find unused dependencies FAILED
    org.spockframework.runtime.SpockComparisonFailure at DependencyServiceSpec.groovy:105

com.netflix.nebula.lint.rule.dependency.DependencyServiceSpec > first level dependencies in conf FAILED
    org.gradle.api.artifacts.ResolveException at DependencyServiceSpec.groovy:157
        Caused by: org.gradle.internal.resolve.ModuleVersionResolveException at DependencyServiceSpec.groovy:157
            Caused by: org.gradle.internal.resolve.ModuleVersionResolveException at DependencyServiceSpec.groovy:157
                Caused by: org.gradle.api.resources.ResourceException at DependencyServiceSpec.groovy:157
                    Caused by: org.gradle.internal.resource.transport.http.HttpRequestException at DependencyServiceSpec.groovy:157
                        Caused by: org.gradle.internal.impldep.org.apache.http.conn.HttpHostConnectException at DependencyServiceSpec.groovy:157
                            Caused by: java.net.ConnectException at DependencyServiceSpec.groovy:157

148 tests completed, 2 failed
:test FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':test'.
> There were failing tests. See the report at: file:///Users/jscancella/development/repos/gradle-lint-plugin/build/reports/tests/index.html

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':test'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
        at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:153)
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:150)
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:98)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:99)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:48)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
        at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:237)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: org.gradle.api.GradleException: There were failing tests. See the report at: file:///Users/jscancella/development/repos/gradle-lint-plugin/build/reports/tests/index.html
        at org.gradle.api.tasks.testing.Test.handleTestFailures(Test.java:1232)
        at org.gradle.api.tasks.testing.Test.executeTests(Test.java:624)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:228)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
        at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:621)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:604)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 68 more


BUILD FAILED

Total time: 2 mins 8.722 secs
```

**Comment by johnscancella** [comment]
I should note that I tried running it again on the test project from before and it now seems to be working...
