### ISSUE TITLE
NPE from overridden dependency version rule

### ISSUE THREAD

**Issue by DanielThomas** [nebula-plugins/gradle-lint-plugin#55]
On, Gradle 2.14.1:

        Caused by: java.lang.NullPointerException
                at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.strategy.DefaultVersionSelectorScheme.parseSelector(DefaultVersionSelectorScheme.java:27)
                at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.strategy.VersionSelectorScheme$parseSelector.call(Unknown Source)
                at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.strategy.VersionSelectorScheme$parseSelector.call(Unknown Source)
                at com.netflix.nebula.lint.rule.dependency.OverriddenDependencyVersionRule.visitGradleDependency(OverriddenDependencyVersionRule.groovy:35)
                at com.netflix.nebula.lint.rule.GradleLintRule.this$dist$invoke$4(GradleLintRule.groovy)
                at com.netflix.nebula.lint.rule.GradleLintRule$1.methodMissing(GradleLintRule.groovy)
                at com.netflix.nebula.lint.rule.GradleLintRule$1.this$dist$invoke$3(GradleLintRule.groovy)
                at com.netflix.nebula.lint.rule.GradleLintRule$1$2.methodMissing(GradleLintRule.groovy)
                at com.netflix.nebula.lint.rule.GradleLintRule$1$2.visitMethodCallInDependencies(GradleLintRule.groovy:398)
                at com.netflix.nebula.lint.rule.GradleLintRule$1$2.visitMethodCallExpression(GradleLintRule.groovy:208)
                at com.netflix.nebula.lint.rule.GradleLintRule$1$2.super$3$visitExpressionStatement(GradleLintRule.groovy)
                at com.netflix.nebula.lint.rule.GradleLintRule$1$2.visitExpressionStatement(GradleLintRule.groovy:345)
                at com.netflix.nebula.lint.rule.GradleLintRule$1$2.super$2$visitMethodCallExpression(GradleLintRule.groovy)
                at com.netflix.nebula.lint.rule.GradleLintRule$1$2.visitMethodCallExpression(GradleLintRule.groovy:215)
                at com.netflix.nebula.lint.rule.GradleLintRule$1$2.super$3$visitExpressionStatement(GradleLintRule.groovy)
                at com.netflix.nebula.lint.rule.GradleLintRule$1$2.visitExpressionStatement(GradleLintRule.groovy:345)
                at com.netflix.nebula.lint.rule.GradleLintRule$1$3$_visitConstructorOrMethod_closure11.doCall(GradleLintRule.groovy:475)
                at com.netflix.nebula.lint.rule.GradleLintRule$1$3.both(GradleLintRule.groovy:419)
                at com.netflix.nebula.lint.rule.GradleLintRule$1$3$both.callCurrent(Unknown Source)
                at com.netflix.nebula.lint.rule.GradleLintRule$1$3.visitConstructorOrMethod(GradleLintRule.groovy:475)
                at com.netflix.nebula.lint.org.codenarc.rule.AbstractAstVisitor.visitMethod(AbstractAstVisitor.java:171)
                at com.netflix.nebula.lint.org.codenarc.rule.AbstractAstVisitor.visitClass(AbstractAstVisitor.java:148)
                at com.netflix.nebula.lint.org.codenarc.rule.AbstractAstVisitorRule.applyTo(AbstractAstVisitorRule.java:97)
                at com.netflix.nebula.lint.org.codenarc.rule.AbstractRule.applyTo(AbstractRule.java:142)
                at com.netflix.nebula.lint.org.codenarc.rule.Rule$applyTo$0.call(Unknown Source)
                at com.netflix.nebula.lint.rule.GradleLintRule.applyTo(GradleLintRule.groovy:135)
                at com.netflix.nebula.lint.org.codenarc.rule.Rule$applyTo$0.call(Unknown Source)
                at com.netflix.nebula.lint.org.codenarc.rule.Rule$applyTo$0.call(Unknown Source)
                at com.netflix.nebula.lint.org.codenarc.analyzer.AbstractSourceAnalyzer.collectViolations(AbstractSourceAnalyzer.groovy:40)
                at com.netflix.nebula.lint.plugin.LintService$ReportableAnalyzer.analyze(LintService.groovy:48)
                at com.netflix.nebula.lint.plugin.LintService$ReportableAnalyzer$analyze.call(Unknown Source)
                at com.netflix.nebula.lint.plugin.LintService$_lint_closure3.doCall(LintService.groovy:96)
                at com.netflix.nebula.lint.plugin.LintService.lint(LintService.groovy:93)
                at com.netflix.nebula.lint.plugin.LintService$lint.call(Unknown Source)
                at com.netflix.nebula.lint.plugin.LintGradleTask.lint(LintGradleTask.groovy:34)
                at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
                at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:228)
                at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
                at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
                at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:621)
                at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:604)
                at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
                at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
                ... 68 more

**Comment by jkschneider** [comment]
@DanielThomas any more specifics on the dependency it blew up on?

**Comment by DanielThomas** [comment]
Will have to debug - will get back to you on that.

**Comment by DanielThomas** [comment]
It's any dependency without a version. In this case, `com.netflix.nebula.lint.rule.GradleDependency(org.springframework.boot, spring-boot-starter-tomcat, null, null, null, null, StringNotation)`

Set a NPE breakpoint, and chokes here:

      "main@1" prio=5 tid=0x1 nid=NA runnable
        java.lang.Thread.State: RUNNABLE
            at java.util.regex.Matcher.getTextLength(Matcher.java:1283)
            at java.util.regex.Matcher.reset(Matcher.java:309)
            at java.util.regex.Matcher.<init>(Matcher.java:229)
            at java.util.regex.Pattern.matcher(Pattern.java:1093)
            at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.strategy.DefaultVersionSelectorScheme.parseSelector(DefaultVersionSelectorScheme.java:27)
            at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.strategy.VersionSelectorScheme$parseSelector.call(Unknown Source:-1)
            at org.codehaus.groovy.runtime.callsite.CallSiteArray.defaultCall(CallSiteArray.java:48)
            at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.strategy.VersionSelectorScheme$parseSelector.call(Unknown Source:-1)
            at com.netflix.nebula.lint.rule.dependency.OverriddenDependencyVersionRule.visitGradleDependency(OverriddenDependencyVersionRule.groovy:35)
            ...

**Comment by kdabir** [comment]
same for me, on Gradle 3.0, Jdk 8:

```
Caused by: java.lang.NullPointerException
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.strategy.DefaultVersionSelectorScheme.parseSelector(DefaultVersionSelectorScheme.java:27)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.strategy.VersionSelectorScheme$parseSelector.call(Unknown Source)
        at org.gradle.api.internal.artifacts.ivyservice.ivyresolve.strategy.VersionSelectorScheme$parseSelector.call(Unknown Source)
        at com.netflix.nebula.lint.rule.dependency.OverriddenDependencyVersionRule.visitGradleDependency(OverriddenDependencyVersionRule.groovy:35)

```
