### ISSUE TITLE
gradle fails with exception

### ISSUE THREAD

**Issue by kudrevatykh** [nebula-plugins/gradle-lint-plugin#72]
after #66 merged I have exception when trying to add criticalRule
```
Caused by: groovy.lang.MissingPropertyException: No such property: level for class: com.netflix.nebula.lint.GradleViolation
        at com.netflix.nebula.lint.GradleLintInfoBrokerAction.buildReportItem(GradleLintInfoBrokerAction.groovy:30)
        at com.netflix.nebula.lint.GradleLintInfoBrokerAction$_lintFinished_closure1$_closure3.doCall(GradleLintInfoBrokerAction.groovy:14)
        at com.netflix.nebula.lint.GradleLintInfoBrokerAction$_lintFinished_closure1.doCall(GradleLintInfoBrokerAction.groovy:14)
        at org.gradle.api.internal.ClosureBackedAction.execute(ClosureBackedAction.java:70)
```

**Comment by jkschneider** [comment]
Thanks for the report @kudrevatykh. Fixed with 08614cdc591262f30c690a4cd4e5864f5dcbcb7b.
