### ISSUE TITLE
autoLintGradle fails with GradleLintRule - processing source file [null]

### ISSUE THREAD

**Issue by mmichaelis** [nebula-plugins/gradle-lint-plugin#88]
I am setting up a multi-module project with gradle-lint-plugin and it fails with this information on info-level:

```
:autoLintGradle (Thread[Daemon worker,5,main]) started.
:autoLintGradle
Putting task artifact state for task ':autoLintGradle' into context took 0.0 secs.
Executing task ':autoLintGradle' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
Error from [com.netflix.nebula.lint.rule.GradleLintRule$1] processing source file [null]
:autoLintGradle FAILED
:autoLintGradle (Thread[Daemon worker,5,main]) completed. Took 6.294 secs.

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':autoLintGradle'.
> 60

* Try:
Run with --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':autoLintGradle'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:84)
	[...]
	at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:34)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:236)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker$1.execute(DefaultTaskGraphExecuter.java:228)
	[...]
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.ArrayIndexOutOfBoundsException: 60
	at org.objectweb.asm.ClassReader.readLabel(Unknown Source)
	at org.objectweb.asm.ClassReader.a(Unknown Source)
	at org.objectweb.asm.ClassReader.a(Unknown Source)
	at org.objectweb.asm.ClassReader.b(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader$accept.call(Unknown Source)
	at com.netflix.nebula.lint.rule.dependency.DependencyService$2.visitFile(DependencyService.groovy:158)
	at com.netflix.nebula.lint.rule.dependency.DependencyService$2.visitFile(DependencyService.groovy)
	at java_nio_file_Files$walkFileTree.call(Unknown Source)
	at com.netflix.nebula.lint.rule.dependency.DependencyService.memoizedMethodPriv$classReferencesString(DependencyService.groovy:153)
	at com.netflix.nebula.lint.rule.dependency.DependencyService$_closure2.doCall(DependencyService.groovy)
	at com.netflix.nebula.lint.rule.dependency.DependencyService.classReferences(DependencyService.groovy)
	at com.netflix.nebula.lint.rule.dependency.DependencyService.memoizedMethodPriv$usedDependenciesString(DependencyService.groovy:258)
	at com.netflix.nebula.lint.rule.dependency.DependencyService$_closure6.doCall(DependencyService.groovy)
	at com.netflix.nebula.lint.rule.dependency.DependencyService.usedDependencies(DependencyService.groovy)
	at com.netflix.nebula.lint.rule.dependency.DependencyService$usedDependencies$13.call(Unknown Source)
	at com.netflix.nebula.lint.rule.dependency.UnusedDependencyRule$_visitGradleDependency_closure1.doCall(UnusedDependencyRule.groovy:58)
	at com.netflix.nebula.lint.rule.dependency.UnusedDependencyRule.visitGradleDependency(UnusedDependencyRule.groovy:57)
	at com.netflix.nebula.lint.rule.GradleLintRule.this$dist$invoke$4(GradleLintRule.groovy)
	at com.netflix.nebula.lint.rule.GradleLintRule$1.methodMissing(GradleLintRule.groovy)
	at com.netflix.nebula.lint.rule.GradleLintRule$1.this$dist$invoke$3(GradleLintRule.groovy)
	at com.netflix.nebula.lint.rule.GradleLintRule$1$2.methodMissing(GradleLintRule.groovy)
	at com.netflix.nebula.lint.rule.GradleLintRule$1$2.visitMethodCallInDependencies(GradleLintRule.groovy:432)
	at com.netflix.nebula.lint.rule.GradleLintRule$1$2.visitMethodCallExpression(GradleLintRule.groovy:212)
	at com.netflix.nebula.lint.rule.GradleLintRule$1$2.super$3$visitExpressionStatement(GradleLintRule.groovy)
	at com.netflix.nebula.lint.rule.GradleLintRule$1$2.visitExpressionStatement(GradleLintRule.groovy:363)
	at com.netflix.nebula.lint.rule.GradleLintRule$1$2.super$2$visitMethodCallExpression(GradleLintRule.groovy)
	at com.netflix.nebula.lint.rule.GradleLintRule$1$2.visitMethodCallExpression(GradleLintRule.groovy:228)
	at com.netflix.nebula.lint.rule.GradleLintRule$1$2.super$3$visitExpressionStatement(GradleLintRule.groovy)
	at com.netflix.nebula.lint.rule.GradleLintRule$1$2.visitExpressionStatement(GradleLintRule.groovy:363)
	at com.netflix.nebula.lint.rule.GradleLintRule$1$3$_visitConstructorOrMethod_closure11.doCall(GradleLintRule.groovy:534)
	at com.netflix.nebula.lint.rule.GradleLintRule$1$3.both(GradleLintRule.groovy:478)
	at com.netflix.nebula.lint.rule.GradleLintRule$1$3$both.callCurrent(Unknown Source)
	at com.netflix.nebula.lint.rule.GradleLintRule$1$3.visitConstructorOrMethod(GradleLintRule.groovy:534)
	at com.netflix.nebula.lint.org.codenarc.rule.AbstractAstVisitor.visitMethod(AbstractAstVisitor.java:171)
	at com.netflix.nebula.lint.org.codenarc.rule.AbstractAstVisitor.visitClass(AbstractAstVisitor.java:148)
	at com.netflix.nebula.lint.org.codenarc.rule.AbstractAstVisitorRule.applyTo(AbstractAstVisitorRule.java:97)
	at com.netflix.nebula.lint.org.codenarc.rule.AbstractRule.applyTo(AbstractRule.java:142)
	at com.netflix.nebula.lint.org.codenarc.rule.Rule$applyTo$0.call(Unknown Source)
	at com.netflix.nebula.lint.rule.GradleLintRule.applyTo(GradleLintRule.groovy:136)
	at com.netflix.nebula.lint.org.codenarc.rule.Rule$applyTo$0.call(Unknown Source)
	at com.netflix.nebula.lint.org.codenarc.rule.Rule$applyTo$0.call(Unknown Source)
	at com.netflix.nebula.lint.org.codenarc.analyzer.AbstractSourceAnalyzer.collectViolations(AbstractSourceAnalyzer.groovy:40)
	at com.netflix.nebula.lint.plugin.LintService$ReportableAnalyzer.analyze(LintService.groovy:48)
	at com.netflix.nebula.lint.plugin.LintService$ReportableAnalyzer$analyze.call(Unknown Source)
	at com.netflix.nebula.lint.plugin.LintService$_lint_closure3.doCall(LintService.groovy:100)
	at com.netflix.nebula.lint.plugin.LintService.lint(LintService.groovy:97)
	at com.netflix.nebula.lint.plugin.LintService$lint.call(Unknown Source)
	at com.netflix.nebula.lint.plugin.LintGradleTask.lint(LintGradleTask.groovy:38)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
	at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
	[...]
```

Build-Script:

* Using `classpath 'com.netflix.nebula:gradle-lint-plugin:latest.release'` in buildscript dependencies of rootProject.
* Applying plugin to allprojects:
    ```
    apply plugin: 'java'
    apply plugin: 'eclipse'
    apply plugin: 'idea'
    apply plugin: 'nebula.lint'
    ```
* Using configuration: `gradleLint.rules += 'all-dependency'`
* Using Gradle 3.3 on Windows

Possibly related to #83? But the error message is different.

**Comment by samkazmi** [comment]
I'm having the same problem, has anyone solved it?

`FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':autoLintGradle'.
> com/incubasys/seventyFirstStreet/Async/AppAsync

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':autoLintGradle'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:66)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:203)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:185)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:66)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:50)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:25)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:110)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
	at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:153)
	at org.gradle.internal.Factories$1.create(Factories.java:22)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:150)
	at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:32)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:98)
	at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:92)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
	at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:92)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:83)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:99)
	at org.gradle.tooling.internal.provider.runner.BuildModelActionRunner.run(BuildModelActionRunner.java:46)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.tooling.internal.provider.runner.SubscribableBuildActionRunner.run(SubscribableBuildActionRunner.java:58)
	at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:48)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:30)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:81)
	at org.gradle.launcher.exec.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:46)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:52)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:237)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
	at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: java.lang.NoClassDefFoundError: com/incubasys/seventyFirstStreet/Async/AppAsync
	at com.sun.beans.TypeResolver.getActualType(TypeResolver.java:376)
	at com.sun.beans.TypeResolver.resolveInClass(TypeResolver.java:96)
	at com.netflix.nebula.lint.rule.dependency.ClassHierarchyUtils.memoizedMethodPriv$typeHierarchyClass(ClassHierarchyUtils.groovy:34)
	at com.netflix.nebula.lint.rule.dependency.ClassHierarchyUtils$__clinit__closure2.doCall(ClassHierarchyUtils.groovy)
	at com.netflix.nebula.lint.rule.dependency.ClassHierarchyUtils.typeHierarchy(ClassHierarchyUtils.groovy)
	at com.netflix.nebula.lint.rule.dependency.ClassHierarchyUtils$typeHierarchy.call(Unknown Source)
	at com.netflix.nebula.lint.rule.dependency.DependencyClassVisitor$_visit_closure3.doCall(DependencyClassVisitor.groovy:100)
	at com.netflix.nebula.lint.rule.dependency.DependencyClassVisitor.visit(DependencyClassVisitor.groovy:98)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader.accept(Unknown Source)
	at org.objectweb.asm.ClassReader$accept.call(Unknown Source)
	at com.netflix.nebula.lint.rule.dependency.DependencyService$2.visitFile(DependencyService.groovy:158)
	at com.netflix.nebula.lint.rule.dependency.DependencyService$2.visitFile(DependencyService.groovy)
	at java_nio_file_Files$walkFileTree.call(Unknown Source)
	at com.netflix.nebula.lint.rule.dependency.DependencyService.memoizedMethodPriv$classReferencesString(DependencyService.groovy:153)
	at com.netflix.nebula.lint.rule.dependency.DependencyService$_closure2.doCall(DependencyService.groovy)
	at com.netflix.nebula.lint.rule.dependency.DependencyService.classReferences(DependencyService.groovy)
	at com.netflix.nebula.lint.rule.dependency.DependencyService.memoizedMethodPriv$unusedDependenciesString(DependencyService.groovy:270)
	at com.netflix.nebula.lint.rule.dependency.DependencyService$_closure7.doCall(DependencyService.groovy)
	at com.netflix.nebula.lint.rule.dependency.DependencyService.unusedDependencies(DependencyService.groovy)
	at com.netflix.nebula.lint.rule.dependency.DependencyService$unusedDependencies$7.call(Unknown Source)
	at com.netflix.nebula.lint.rule.dependency.UnusedDependencyRule.visitGradleDependency(UnusedDependencyRule.groovy:56)
	at com.netflix.nebula.lint.rule.GradleLintRule.this$dist$invoke$4(GradleLintRule.groovy)
	at com.netflix.nebula.lint.rule.GradleLintRule$1.methodMissing(GradleLintRule.groovy)
	at com.netflix.nebula.lint.rule.GradleLintRule$1.this$dist$invoke$3(GradleLintRule.groovy)
	at com.netflix.nebula.lint.rule.GradleLintRule$1$2.methodMissing(GradleLintRule.groovy)
	at com.netflix.nebula.lint.rule.GradleLintRule$1$2.visitMethodCallInDependencies(GradleLintRule.groovy:432)
	at com.netflix.nebula.lint.rule.GradleLintRule$1$2.visitMethodCallExpression(GradleLintRule.groovy:212)
	at com.netflix.nebula.lint.rule.GradleLintRule$1$2.super$3$visitExpressionStatement(GradleLintRule.groovy)
	at com.netflix.nebula.lint.rule.GradleLintRule$1$2.visitExpressionStatement(GradleLintRule.groovy:363)
	at com.netflix.nebula.lint.rule.GradleLintRule$1$2.super$2$visitMethodCallExpression(GradleLintRule.groovy)
	at com.netflix.nebula.lint.rule.GradleLintRule$1$2.visitMethodCallExpression(GradleLintRule.groovy:228)
	at com.netflix.nebula.lint.rule.GradleLintRule$1$2.super$3$visitExpressionStatement(GradleLintRule.groovy)
	at com.netflix.nebula.lint.rule.GradleLintRule$1$2.visitExpressionStatement(GradleLintRule.groovy:363)
	at com.netflix.nebula.lint.rule.GradleLintRule$1$3$_visitConstructorOrMethod_closure11.doCall(GradleLintRule.groovy:534)
	at com.netflix.nebula.lint.rule.GradleLintRule$1$3.both(GradleLintRule.groovy:478)
	at com.netflix.nebula.lint.rule.GradleLintRule$1$3$both.callCurrent(Unknown Source)
	at com.netflix.nebula.lint.rule.GradleLintRule$1$3.visitConstructorOrMethod(GradleLintRule.groovy:534)
	at com.netflix.nebula.lint.org.codenarc.rule.AbstractAstVisitor.visitMethod(AbstractAstVisitor.java:171)
	at com.netflix.nebula.lint.org.codenarc.rule.AbstractAstVisitor.visitClass(AbstractAstVisitor.java:148)
	at com.netflix.nebula.lint.org.codenarc.rule.AbstractAstVisitorRule.applyTo(AbstractAstVisitorRule.java:97)
	at com.netflix.nebula.lint.org.codenarc.rule.AbstractRule.applyTo(AbstractRule.java:142)
	at com.netflix.nebula.lint.org.codenarc.rule.Rule$applyTo$0.call(Unknown Source)
	at com.netflix.nebula.lint.rule.GradleLintRule.applyTo(GradleLintRule.groovy:136)
	at com.netflix.nebula.lint.org.codenarc.rule.Rule$applyTo$0.call(Unknown Source)
	at com.netflix.nebula.lint.org.codenarc.analyzer.AbstractSourceAnalyzer.collectViolations(AbstractSourceAnalyzer.groovy:40)
	at com.netflix.nebula.lint.plugin.LintService$ReportableAnalyzer.analyze(LintService.groovy:48)
	at com.netflix.nebula.lint.plugin.LintService$ReportableAnalyzer$analyze.call(Unknown Source)
	at com.netflix.nebula.lint.plugin.LintService$_lint_closure3.doCall(LintService.groovy:100)
	at com.netflix.nebula.lint.plugin.LintService.lint(LintService.groovy:97)
	at com.netflix.nebula.lint.plugin.LintService$lint.call(Unknown Source)
	at com.netflix.nebula.lint.plugin.LintGradleTask.lint(LintGradleTask.groovy:38)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:228)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:221)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:210)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:621)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:604)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 70 more


BUILD FAILED`

**Comment by samkazmi** [comment]
i tried using 
`autoLintGradle.dependsOn subprojects*.build` after `apply plugin: 'nebula.lint'`

it gives ````Error:(18, 0) Could not get unknown property 'build' for project ':71ststreetapi' of type org.gradle.api.Project.``` 

71ststreetapi is a module i'm using in my app

**Comment by jkschneider** [comment]
@mmichaelis issue is probably related to an ASM bug reported [here](http://forge.ow2.org/tracker/index.php?func=detail&aid=317615&group_id=23&atid=100023) and discussed in an easier to digest form [here](https://jira.spring.io/browse/SPR-14089)

**Comment by jkschneider** [comment]
@samkazmi your issue is unrelated, but looks to be easy to solve as well with a little more defensive exception handling in `ClassHierarchyUtils`
